/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
//        Restaurant restaurant1 = new Restaurant("Delicious Eats", 3 );
//        Review review1 = new Review("Great food and atmosphere!", "Alice", 5,restaurant1);
//        Review review2 = new Review("Service could be better, but tasty food.", "Bob", 3,restaurant1);
        Restaurant restaurant2 = new Restaurant("Mosuab", 3);
        Review review3 = new Review("bad", "ahmad", 4,restaurant2);
        Review review4 = new Review("verry bad", "waleed", 2,restaurant2);
        restaurant2.addReview(review3);
        restaurant2.addReview(review4);
//        restaurant1.addReview(review1);
//        restaurant1.addReview(review2);
//        System.out.println(restaurant1);
//        System.out.println(review1);
//        System.out.println(review2);
        System.out.println(restaurant2);
        System.out.println(review3);
        System.out.println(review4);
    }
    }

