/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

        @Test
        void restaurantConstructorTest() {
            Restaurant restTest = new Restaurant("Papi",35);
            assertEquals(restTest.getName(), "Papi");
            assertEquals(restTest.getPriceCategory(), 35);

        }
    @Test
    void testRestaurantToString() {
        Restaurant restaurant = new Restaurant("Mosuab Restaurant", 4);
        String expected = "Restaurant{name='Mosuab Restaurant', stars=0.0, priceCategory=4}";
        assertEquals(expected, restaurant.toString());
    }

    @Test
    void reviewConstructorTest() {
            Restaurant test=new Restaurant("Mosuab Restaurant", 4);
        Review reviewTest = new Review("Great food", "Mosuab",5,test);
        assertEquals(reviewTest.getBody(), "Great food");
        assertEquals(reviewTest.getAuthor(), "Mosuab");
        assertEquals(reviewTest.getStars(), 5);


    }
    @Test
    void testReviewToString() {
        Restaurant testRestaurant = new Restaurant("Mosuab Restaurant", 4);
        Review reviewTest = new Review("Great food!", "Mosuab", 5, testRestaurant);
        String expected = "Review{author='Mosuab', stars=5, body='Great food!'}";
        assertEquals(expected, reviewTest.toString());
    }
    @Test
    void testRestaurantReviewAssociation() {
        Restaurant testRestaurant = new Restaurant("Test Restaurant", 3);
        Review review = new Review("Delicious dishes", "Alice", 4, testRestaurant);

        assertEquals(0.0, testRestaurant.getStars());

        testRestaurant.addReview(review);
        assertEquals(4.0, testRestaurant.getStars());

        testRestaurant.addReview(review);
        assertEquals(4.0, testRestaurant.getStars());
    }

    }

